apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dev-test
    tier: backend
  name: dev-test-deploy
  namespace: dev-test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-test
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dev-test
        tier: backend
    spec:
      containers:
      - image: hectorfaria/dev-test
        imagePullPolicy: Always
        name: dev-test
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 50Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always