name: Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & Cache dependencies
        uses: ./.github/actions/cached-deps/
      - name: Lint code
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & Cache dependencies
        uses: ./.github/actions/cached-deps/
      - name: Test Code
        id: run-tests
        run: npm run test
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & Cache dependencies
        uses: ./.github/actions/cached-deps/
      - name: Coverage the tests
        id: coverage-test
        run: npm run coverage
    outputs:
      coverage: ${{ steps.coverage-test.outputs }}
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & Cache dependencies
        uses: ./.github/actions/cached-deps/
      - name: Check for vulnerabilities
        run: npm run scan
        id: scan-code
    outputs:
        coverage: ${{ steps.scan-code.outputs }}